spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jpa?serverTimezone=UTC-9&characterEncoding=UTF-8
    username: root
#    password: 비번

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create #create update none #create는 매번 table을 drop후 새로 생성 #update는 table drop 없이 변경된 부분만 업데이트
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

security:
  oauth2:
    client:
      registration:
        google:
          client-id: 9592862241-hnr82j4190ncah9vmck12gde2ae8t9ig.apps.googleusercontent.com
          client-secret: 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
          scope:
            - email
            - profile

        facebook:
          client-id: 522515432828715
          client-secret: 93d8f4ce29972cc6fa3c7962cc3e2cdb
          scope:
            - email
            - public_profile

        naver:
          client-id: me8ebXksJDqRH490hSpa
          client-secret: ClmR3qkb6U
          scope:
            - name
            - email
          client-name: Naver
          authorization-grant-type: authorization_code
          # 구글이나 페이스 북은 redirect-uri를 안 적어줘도 된다.
          # 디폴트로 'http://localhost:8080/login/oauth2/code/{google, facebook}'설정되어 있기 때문이다.
          # 주의해야 할 점은 google이나 facebook은 경로가 고정되어 있어 바꾸게 되면 제대로된 응답을 받을 수 없다.
          # naver는 redirect 경로가 정해져 있지 않기 때문에 마음대로 설정이 가능하다.
          redirect-uri: http://localhost:8080/login/oauth2/code/naver

      # 네이버는 기본적으로 프로바이더로 등록이 되어있지 않기 때문에 등록해줘야 한다
      provider:
        naver:
          authorization-uri: https://nid.naver.com/oauth2.0/authorize # 네이버 로그인창 주소
          token-uri: https://nid.naver.com/oauth2.0/token # 토큰 발급 uri
          user-info-uri: https://openapi.naver.com/v1/nid/me # 프로필 정보를 받기 위한 uri
          # 회원정보를 json으로 받는데 response라는 키값으로 네이버가 리턴해줌
          # response키의 값이 oauth2User.getAttributes()해서 나오는 회원정보다
          user-name-attribute: response

logging:
  level:
    root: info #trace, debug, info, warn, error